### PR TITLE
Bump quickcheck to 0.6

### PR DESCRIPTION
**Pull request by tormol**
The bump to 0.5 haven't been released

### CODE REVIEW

**Comment by tomprogrammer** [comment]
This one requires a major version change, right?

**Comment by tormol** [comment]
Not any more than [bumping it to 0.5](https://github.com/tomprogrammer/rust-ascii/pull/46) already did.
(I assumed the next release was going to be a point release anyway, due to d2fe1d79e40e940a, but I now realize that was three months earlier).
For a point release you should revert to quickcheck 0.4 first.

**Comment by tomprogrammer** [comment]
Ah, I didn't release the last quickcheck update. So #48 will be release in version 0.8.7 and this PR will be released in version 0.9.0

**Comment by tomprogrammer** [comment]
I've merge this PR manually.

**Pull request closed without merging**
