### PR TITLE
No std fns

### PR DESCRIPTION
**Pull request by tormol**

### CODE REVIEW

**Comment by tomprogrammer** [comment]
The methods you added don't have documentation comments. You don't need to add them, I can rebase my commit on yours.

**Comment by tormol** [comment]
The methods are not going to show up in the online rustdoc unless you pass --features no_std, and then AsciiString is missing. 

I'll update the readme soon.

**Comment by tomprogrammer** [comment]
I've opened issue #27 for that.

**Comment by tormol** [comment]
Not exactly soon..

I made an attempt at generating multiple docs on travis, but that part doesn't run on pull requests so I can't test it.

**Comment by tomprogrammer** [comment]
I guess it should work, so I just merge this into master. If necessary it can be fixes directly in master.

**Comment by tormol** [comment]
It worked!

**Pull request merged**
